# Generated by Django 3.1.6 on 2021-02-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pattern',
            fields=[
                ('patternField', models.TextField()),
                ('ptn_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
