# Generated by Django 3.1.6 on 2021-02-22 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pattern',
            new_name='patterns',
        ),
    ]
