# Generated by Django 3.1.6 on 2021-04-09 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0004_auto_20210409_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcollection',
            name='check_confirm',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='requestcollection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestcollection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
