# Generated by Django 3.1.6 on 2021-04-09 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0005_auto_20210409_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcollection',
            old_name='check_confirm',
            new_name='status_check',
        ),
    ]
