# Generated by Django 3.1.6 on 2021-04-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0006_auto_20210409_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcollection',
            name='category_type',
        ),
    ]
