# Generated by Django 3.1.6 on 2021-04-09 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0007_remove_requestcollection_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcollection',
            name='category_type',
            field=models.CharField(choices=[('Trick Question', 'Trick Question'), ('Sneak into Basket', 'Sneak into Basket'), ('Forced Continuity', 'Forced Continuity'), ('Misdirection', 'Misdirection'), ('Price Comparison Prevention', 'Price Comparison Prevention'), ('Force Cookies', 'Force Cookies'), ('Urgency', 'Urgency'), ('Confirmshaming', 'Confirmshaming'), ('Hidden costs', 'Hidden costs')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
