# Generated by Django 3.1.6 on 2021-04-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0009_auto_20210409_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcollection',
            name='desc',
            field=models.TextField(),
        ),
    ]
