# Generated by Django 3.1.6 on 2021-04-09 18:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0010_auto_20210409_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcollection',
            name='category_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Trick Question', 'Trick Question'), ('Sneak into Basket', 'Sneak into Basket'), ('Forced Continuity', 'Forced Continuity'), ('Misdirection', 'Misdirection'), ('Price Comparison Prevention', 'Price Comparison Prevention'), ('Force Cookies', 'Force Cookies'), ('Urgency', 'Urgency'), ('Confirmshaming', 'Confirmshaming'), ('Hidden costs', 'Hidden costs')], max_length=141),
        ),
    ]
