# Generated by Django 3.1.6 on 2021-04-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0011_auto_20210409_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('ptn_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('total_count', models.IntegerField()),
                ('categories', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Tracked List',
            },
        ),
    ]
