# Generated by Django 3.1.6 on 2021-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0012_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='patternCategory',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Pattern Category',
            },
        ),
        migrations.AlterModelOptions(
            name='requestcollection',
            options={'verbose_name_plural': 'Request Track'},
        ),
    ]
