# Generated by Django 3.1.6 on 2021-04-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0013_auto_20210410_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patterncategory',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
